### ISSUE TITLE
ERROR: #0 [internal function]()

### ISSUE THREAD

**Issue by Fossil01** [thephpleague/climate#187]
I have been getting quite a few of these in my Laravel error logs. Running PHP 8.1.1 right now.

```
[2022-02-07 15:32:59] REMOVED.ERROR: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/REMOVED/vendor/league/climate/src/Util/Writer/StdOut.php(14): fwrite()
#2 /var/www/REMOVED/vendor/league/climate/src/Util/Output.php(183): League\CLImate\Util\Writer\StdOut->write()
#3 /var/www/REMOVED/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(37): League\CLImate\Util\Output->write()
#4 /var/www/REMOVED/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute()
#5 /var/www/REMOVED/vendor/league/climate/src/CLImate.php(384): League\CLImate\TerminalObject\Router\Router->execute()
#6 /var/www/REMOVED/vendor/league/climate/src/CLImate.php(399): League\CLImate\CLImate->buildTerminalObject()
#7 /var/www/REMOVED/vendor/league/climate/src/CLImate.php(435): League\CLImate\CLImate->routeRemainingMethod()
#8 /var/www/REMOVED/Blacklight/ColorCLI.php(94): League\CLImate\CLImate->__call()
#9 /var/www/REMOVED/Blacklight/REMOVED.php(997): Blacklight\ColorCLI->primary()
#12 {main}
```

```php
$this->colorCli->primary('Some sprintf formatted string goes here');
```

**Comment by duncan3dc** [comment]
Hi @Fossil01 it's difficult to tell what your error is as the actually error message appears to have been removed, are you able to post the error message being raised from `StdOut.php`?

**Comment by duncan3dc** [comment]
Are you able to provide a small reproduction script instead then?

**Comment by Fossil01** [comment]
I'll try in the next few days. Sick in bed currently -.-

**Comment by duncan3dc** [comment]
Get well soon!
